# Generated by Django 3.0.3 on 2020-08-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='timestamp',
        ),
    ]
