# Generated by Django 3.0.3 on 2020-08-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200802_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likeType',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikeCount',
        ),
    ]
